#!/bin/bash


sed -i "/PasswordAuthentication no/d" /etc/ssh/sshd_config
echo "" | sudo tee -a /etc/ssh/sshd_config
echo "" | sudo tee -a /etc/ssh/sshd_config
echo "PermitRootLogin yes" | sudo tee -a /etc/ssh/sshd_config
echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
systemctl restart sshd
ip=$(curl ifconfig.me/ip)
clear
sleep 1
printf "
 ____           _             _ 
|  _ \    ___  | |_    ___   | |
| | | |  / _ \ | __|  / _ \  | |
| |_| | |  __/ | |_  | (_) | | |
|____/   \___|  \__|  \___/  |_|
"                                
echo
echo "Cara Mudah Untuk Root Dan Login Vps"
echo "============================================"
user=root
length=$[ 8 +$[RANDOM % 16]]

char=(0 1 2 3 4 5 6 7 8 9 a b c d e f g h i j k l m n o p q r s t u v w x y z A B C D E F G H I J K L M N O P Q R S T U V W X Y Z ! @ \# $ % ^ \&)

max=${#char[*]}
for ((i = 1; i <= $length ; i++))do

let rand=${RANDOM}%${max}
password="${password}${char[$rand]}"
done
echo "Masukkan Masa Aktif: "
read -e ak
exp=$(date -d "$ak days" +"%d-%m-%Y")
crt=$(date -d "0 days" +"%d-%m-%Y")
pwe=$(mkpasswd $password)

clear
usermod --password $pwe $user
clear

echo ""
printf "Please Save This VPS Account Information
============================================
Ip address = $ip
Username   = $user
Password   = $password
Expired    = $exp
Created    = $crt
============================================"
sleep 1
echo ""
echo 
exit
